### ISSUE TITLE
key caps

### ISSUE THREAD

**Issue by depperson** [KK4TEE/3DSKY#2]
What did you use for the key caps?

**Comment by KK4TEE** [comment]
I used a 3D printed flat square keycap with a cherry MX compatible base. It
looks like I forgot to include it with the rest of the model files, but
I'll see if I can track it down and upload it for you.

**Comment by marccardinal** [comment]
Did you have a chance to take a look?

**Comment by KK4TEE** [comment]
Found it! It's now included along with the other openSCAD files.

**Comment by mcardinalupgrade** [comment]
Thanks Man!
